global:
  ## Hyperkube image to use when getting ThirdPartyResources & cleaning up
  ##
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.7.2_coreos.0
    pullPolicy: IfNotPresent

## Prometheus-operator image
##
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.11.0
  pullPolicy: IfNotPresent

## Node labels for prometheus-operator pod assignment
##
nodeSelector: {}

## If true, create & use RBAC resources
##
rbacEnable: false

## If true, collect & send anonymous usage statistics
## Ref: https://github.com/coreos/prometheus-operator#installation
##
sendAnalytics: false

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources: 
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

## The prometheus operator will create an endpoint for the kubelet.
## Format: namespace/name
##
kubeletObject:
  enable: true
  object: kube-system/kubelet
